# Generated by Django 6.0.3 on 2026-07-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scf_cf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='submitted_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
